### ISSUE TITLE
Karpenter nodes fail to join cluster due to missing EKS Access Entry for Karpenter node role

### ISSUE THREAD

**Issue by matwerber1** [awslabs/ai-on-eks#111]
## Description

The  base Terraform stack in `infra/base/terraform/*` fails to add the Karpenter node role to the awsauth config map or add an appropriate EKS Access Entry to allow Karpenter-launched nodes to join the cluster. None of the specific examples do this either, with the exception of `infra/nvidia-triton-server/eks.tf`. 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 
`terraform-aws-modules/eks/aws`, version `~> 20.34`

- Terraform version:
Terraform v1.11.2
on darwin_arm64

- Provider version(s):
+ provider registry.terraform.io/cloudposse/utils v1.30.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.19.0
+ provider registry.terraform.io/hashicorp/archive v2.7.1
+ provider registry.terraform.io/hashicorp/aws v5.99.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.7
+ provider registry.terraform.io/hashicorp/helm v2.17.0
+ provider registry.terraform.io/hashicorp/http v3.5.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.37.1
+ provider registry.terraform.io/hashicorp/null v3.2.4
+ provider registry.terraform.io/hashicorp/random v3.7.2
+ provider registry.terraform.io/hashicorp/time v0.13.1
+ provider registry.terraform.io/hashicorp/tls v4.1.0

## Reproduction Code

No 

Yes

1. Deploy any of the examples with Karpenter enabled (*excluding* `infra/nvidia-triton-server/eks.tf`, which include the needed authmap entry)

2. Run any pod/workload matching one of the nodeclass/nodepool definitions in `infra/base/terraform/addons.tf`

3. Inspect Karpenter nodeclaims. You should see a node claim that fails to reach a ready state with status similar to below:

```
 conditions:
  - lastTransitionTime: "2025-06-25T05:47:08Z"
    message: object is awaiting reconciliation
    observedGeneration: 1
    reason: AwaitingReconciliation
    status: Unknown
    type: Initialized
  - lastTransitionTime: "2025-06-25T05:47:08Z"
    message: Node not registered with cluster
    observedGeneration: 1
    reason: NodeNotFound
    status: Unknown
    type: Registered
  - lastTransitionTime: "2025-06-25T05:47:10Z"
    message: ""
    observedGeneration: 1
    reason: Launched
    status: "True"
    type: Launched
  - lastTransitionTime: "2025-06-25T05:47:08Z"
    message: Initialized=Unknown, Registered=Unknown
    observedGeneration: 1
    reason: ReconcilingDependents
    status: Unknown
    type: Ready
  imageID: ami-0f18ea0dac0257b4d
  providerID: aws:///us-east-2b/i-0f61b351d26d3809e
```

4. I can see the instance in a running state in EC2 console, instance system logs don't show an error, but every (5, 10?) minutes, Karpenter eventually kills off the instance and starts a new one; same issue occurs.

## Expected behavior

Node launched, joins cluster, pod runs.

## Actual behavior

See above. 

## Additional info 

V20 of module `terraform-aws-modules/eks/aws` introduced a breaking change whereby the eks module no longer exposes an `aws_auth_roles` configuration option due to EKS shifting to Access Entries and having awsauth config map on a deprecation path. 
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/3077

In prior versions of the module, as well older versions of this project (and the slightly out-of-sync examples on the ), the `aws_auth_roles` config was used like below to give the Karpenter node role proper permissions for an EC2 instance to join the cluster:

```hcl
module "eks" {

  manage_aws_auth_configmap = true

  aws_auth_roles = [
    {
      rolearn  = data.aws_iam_role.karpenter_instance.arn
      username = "system:node:{{EC2PrivateDNSName}}"
      groups   = ["system:bootstrappers", "system:nodes"]
    },
  ]
  aws_auth_users = var.eks_additional_users
...
}
```

V20 of the eks module has replaced aws_auth_roles with access_entries that can be used to give roles neccessary permissions for joining a node to the cluster but this won't work for Karpenter in this example project because we'd be creating a circular reference referring to module.eks_blueprints_addons.karpenter.node_iam_role_arn in the eks module. 

At least for me, I just added a separate `aws_eks_access_entry` resource. Shortly after running terraform apply, my node was now joined to the cluster, the nodeclaim errors were gone, and my pod started.

```hcl
resource "aws_eks_access_entry" "karpenter_nodes" {
  cluster_name  = module.eks.cluster_name
  principal_arn = module.eks_blueprints_addons.karpenter.node_iam_role_arn
  type          = "EC2_LINUX"
}
```
